### ISSUE TITLE
Nice mod, but just one request.

### ISSUE THREAD

**Issue by spolen88** [Sonderkugel/expanded-alerts#2]
I'm gonna try out this mod in a bit, but I have to ask, would you be able to take "everything" out of the issues tab and make them alerts? I honestly have no clue why the issues tab was even added to the game in the first place.

**Comment by Sonderkugel** [comment]
There's so many little alerts in the Issues tab that I think I want to limit alerts to high priority things. Having all these at the top of the screen would be overwhelming and pretty spammy so things that don't require immediate attention are gonna be kept there for now.
